Ellypse/Total-RP-3-Extended

- totalRP3_Extended/dialogues/dialogues.lua
- totalRP3_Extended/locale.lua
I've removed the "Next step index" text at the bottom of cutscene dialogs. It was confusing, annoying, and served no purpose.
To compensate since I was there, I replaced it with a text to "Choose an option" when there are player choices, to make it coherent with the "Wait for loot" text.
> Issue #45 : "Next step index" cutscene bottom text

- totalRP3_Extended/quest/quest_log.lua
- totalRP3_Extended/script/script_generation.lua
- totalRP3_Extended_Tools/main.lua
Variables are now automatically truncated to 2 decimals when parsed. You can use ${variable#X} to truncate a variable to X decimals.
I'm also flooring the campaign progress percentage, as it doesn't really need decimal precision.
> Issue #19 : Truncating variables decimals

- totalRP3_Extended/script/script_effects.lua
To prevent successive prompts issues, added a delay of 100 ms before calling the optional workflow.
I also fixed the workflow condition, which was inappropriately displaying an error message `Can't find workflow ""` when no workflow was optionally added.
> Issue #9 : Delay before workflow callback from prompt

- totalRP3_Extended/locale.lua
- totalRP3_Extended_Tools/inner/inner.lua
If the player inputs an ID containing at least one space character, it shows an alert popup reminding not to use them instead of creating the object and breaking everything.
*Locale at the bottom \o/*
> Issue #18 : Added an alert popup when given inner ID has a space

- totalRP3_Extended/inventory/inventory_drop.lua
Thanks to Meorawr's answer on the TRP ticket, managed to fix both stashes scan icon issues ( TRP3 \#120 & Extended #93 ).
The stashes now have the proper icon again, and it gets reset correctly when doing a character scan afterwards.
> Wrong icons when scanning stashes + reset bug

- totalRP3_Extended/inventory/inventory_exchange.lua
- totalRP3_Extended/inventory/inventory_page.lua
- totalRP3_Extended/locale.lua
*It's taken me all of 10 minutes to copy-paste your previous work on it from Kaji's repository (+ 10 minutes to test), and I still had to fix the locale keys so I'll pretend it's my work. Fite me.*
This adds a trade button to the TRP3 target frame which opens an empty trade with your target. Button doesn't appear if the target is an NPC or doesn't have Extended.
> Issue #59 : Trade button in the target frame

- totalRP3_Extended/main.lua
This just adds the sender's name as the signal's 3rd argument. Doesn't change the broadcast message arguments, so it will work with signals from previous versions.
*Also removed a copy-pasted format.*
> Issue #48 : Adding sender to TRP3_SIGNAL arguments

- totalRP3_Extended/script/script_generation.lua
Restricted scripts can now access variables.
- getVar(args, source, varName)
- setVar(args, source, varName, varValue)
[source : "w" for workflow, "o" for object or "c" for campaign]
[varName : the name of the variable as a string (ex : "my_variable")]
*I'm planning on adding a small wiki article to explain the restricted script available functions - while repeating warnings about performance and lack of clarity for other players.*
> Issue #46 : Added variable access in the script effect

- totalRP3_Extended/inventory/inventory_drop.lua
- totalRP3_Extended/locale.lua
Added a new field in stash info storing the name of the character who first creates the stash, as well as an option in the stash dropdown to change this to the currently played character.
Simply editing the stash will not change the stash's creator.
This change is not retroactive (as the creator's name wasn't stored initially), so previously created stashes will need to use the new dropdown option to set a creator (or they will keep the current behaviour).
> Issue #70 : Show creator's name instead of current played character

- totalRP3_Extended/locale.lua
- totalRP3_Extended/main.lua
- totalRP3_Extended_Tools/links/links.lua
- totalRP3_Extended_Tools/links/links.xml
Changed TRP3_KILL arguments in the case of a player kill, so that it returns info on the player killed (class/race/gender).
Since TRP3_KILL wasn't documented, I added an article to the wiki detailing how this event (as well as TRP3_SIGNAL) work and linked to it in the in-game tutorial.
*I don't want to hear about HTML ever again.*
> Issue #84 : TRP3_KILL arguments change for player kill

- totalRP3_Extended/inventory/container.lua
- totalRP3_Extended/inventory/inventory.lua
Loot all was stopping every time it encountered a stack, asking for how much stacks the player wanted to loot. Loot all doesn't ask anymore, trying to loot everything it can (and still stopping when it cannot loot anymore).
Small bonus fix : when it cannot loot anymore, it would show "Received [non-looted item] x0". I added a check so that the message (and the inventory refresh that goes with it) doesn't happen if we're adding 0 of an item.
> Issue #12 : "Loot all" effect fix

- totalRP3_Extended_Tools/cutscene/editor/normal.lua
Clicking "Condition" for a player choice would add a condition to that choice directly, which would stay even if the condition editor was exited without saving (without actually showing it without refreshing the choices frame). The condition now stays nil until it's actually saved.
> Issue #15 : Not adding condition to player choice before saving

- totalRP3_Extended/locale.lua
- totalRP3_Extended_Tools/inner/inner.lua
- totalRP3_Extended_Tools/items/editor/quick.lua
- totalRP3_Extended_Tools/items/editor/quick.xml
- Added a button in the item templates to create a blank expert item.
- Changed the item templates buttons layout so the height wouldn't get crazy.
- To both simplify the conversion to expert mode for inner items and solve the bug when copying quick items, inner items will now automatically set their mode to the same as their parent (exception : if the source item is expert and the parent is normal, the inner item will stay expert).
> Issues #22 & #74 : Changes regarding item creation modes

- totalRP3_Extended_Tools/list/list.lua
When shift-clicking from the database to create a link, there was a debug instruction left to inspect the data table, I tracked it down and removed it.
Also merge my dice roll PR 😡
> Removed debug inspect table

- totalRP3_Extended/inventory/inventory_effects.lua
- totalRP3_Extended/locale.lua
- totalRP3_Extended_Tools/items/effects.lua
- totalRP3_Extended_Tools/items/items.xml
Added fields to enter a variable name & source to the dice roll effect editor. If empty, the roll works as it currently does. Else, it will (shockingly) store the dice roll result in the given variable.
> Issue #27 : Store dice roll result in a variable

- totalRP3_Extended/dialogues/dialogues.xml
- totalRP3_Extended/document/document.xml
- totalRP3_Extended/inventory/inventory.xml
- totalRP3_Extended/misc/cast.xml
- Some templates copied from Blizzard had their event functions replaced by "nil" which threw an error on load, since "nil" isn't a function. I replaced them with an empty string, which doesn't throw an error.
- There was a reference to a db.lua file that doesn't exist in the document folder (and shouldn't exist, as documents can't be creations by themselves)
> A couple of minor fixes

- totalRP3_Extended/inventory/container.lua
- totalRP3_Extended/locale.lua
- totalRP3_Extended/main.lua
- totalRP3_Extended_Tools/list/list.lua
- totalRP3_Extended_Tools/main.lua
Soooo, changes to compensate for the build/version number shenanigans.
- Added the version number in the globals (extended_display_version)
- Added a field "dV" (for display version) in the creations. This field is used to display the version number if present, else it tries to format the build number.
- Version formatting function has cases for the 3 decoupled versions.
- Changed import/export functions to keep track of the version number as well. Tested exporting/importing through wago for cases with and without the version number, no issue.
I also fixed a small typo while I was at it, didn't want to branch just for this.
We could use the version number instead of the build number in the TRP modules list, depending on your opinion.
> Changes to version number display + small typo fix

- totalRP3_Extended/locale.lua
- totalRP3_Extended_Tools/script/effects/effects.lua
It was already possible to summon a random favourite mount, but it wasn't obvious (happened when you didn't set a mount) and you couldn't set it again after selecting a mount (other than deleting the effect and doing it again).
Right-clicking on the icon now removes the selected mount, and the "No mount selected" indicator has been replaced to indicate the effect will summon a random favourite mount. As far as I know, there is no option to summon a random mount from the entire pool.
> Summon random favourite mount

- totalRP3_Extended/inventory/db.lua
- totalRP3_Extended/misc/sounds.lua
- totalRP3_Extended/script/script_effects.lua
- totalRP3_Extended_Tools/script/effects/effects.lua
- The "Simple rifle" database item had a condition reworked some time ago so it wasn't working, fixed it.
- EJ_GetCurrentInstance has been removed, replaced by C_Map.GetBestMapForUnit. ~~I haven't been able to find the justification for having the first function in the first place, and the new one would cause trouble for people on the border of a map change. For this reason, I just removed it until further notice.~~ It seems it might have been useful when sounds could be played in instances, with multiple floors/maps, not the case anymore.
- There were some missing nil checks in the sound effects.
> Minor fixes

- totalRP3_Extended/locale.lua
- totalRP3_Extended/script/script_effects.lua
- totalRP3_Extended_Tools/script/effects/effects.lua
- totalRP3_Extended_Tools/script/effects/effects.xml
While testing all effects, I stumbled upon a mistake : the "Summon random pet" effect said it was pulling from the favourite pets pool in the tooltip, but the effect was actually pulling from the entire pool.
Instead of only correcting the tooltip, I changed the effect to allow for summoning from either the entire pool or the favourite pool.
> Random battle pet summon now allows to pull from favourites only

- totalRP3_Extended/inventory/inventory_exchange.lua
I only realized while looking at the settings : when I copied the old code for the trade button, I didn't realize the locale key for the config setting was wrong. Fixing it so it doesn't look like the same key is there twice.
> Wrong locale key for trade button setting

- totalRP3_Extended/locale.lua
- totalRP3_Extended_Tools/items/effects.lua
- totalRP3_Extended_Tools/items/items.xml
- All effects and conditions used "Search in: *Source*" in the dropdown, which didn't make sense for the "Add item" effect. "Add item" now says "Add to: *Source*". Locale keys were updated to reflect that there can now be multiple wordings for selecting the inventory source.
- As to what was discussed about disabling the invalid dropdown choices : as far as I'm understanding, the editor doesn't easily know the creation where it's called from, so it doesn't seem easy to implement. Likewise, an alert message when using an invalid source doesn't seem easily possible for conditions, and my tests trying to add one to the effects weren't successful either.
Given that the scope of those sources is clearly explained in the tooltip shown when hovering those options, and the updated locale for "Add …
> Inventory effects/conditions small fixes

- totalRP3_Extended/totalRP3_Extended.toc
As said in #126, we currently get a `Couldn't find inherited node: QuestChoiceLeftHide, QuestChoiceRightHide, QuestChoiceBottomHide` Lua error on load. Since there hasn't been a fix since, and finding the missing dependency would probably be tricky, an optional dependency has been added to compensate.
The need for this dependency should probably be reevaluated in future updates. Maybe if we have enough time to waste, we can track which part of the code triggers the error to report it to Blizzard.
> Adding dependency to fix Blizz missing dependency

- totalRP3_Extended/inventory/inventory_drop.lua
- totalRP3_Extended/misc/sounds.lua
- Searching for other players' stashes wasn't working because I used the wrong function to replace GetCurrentMapID when starting the request.
- Broadcasting a local sound/music wasn't working because the removal of the string concatenation with EJ_GetCurrentInstance caused instanceID and myInstanceID to be different types (instanceID, coming from a broadcast command, was a string).
Also maybe I should get my eyes checked because I didn't realize when removing the concatenation that it created useless lines...
> Fixes for some broadcast issues

- totalRP3_Extended_Tools/list/list.lua
As discussed before, added LibDeflate compression and encoding to Extended's quick import/export. The new exported string has a `!` added at the beginning of the string so there isn't a need to test and fail to know if it is an old or new string.
The parenthesis characters are also switched to `+` and `=` to avoid any potential formatting issue when sharing the string. Not 100% sure if that is necessary.
> Added compression for import/export

- totalRP3_Extended/script/script_generation.lua
- totalRP3_Extended_Tools/script/conditions/conditions.lua
When you select a condition which needs arguments, a popup appears to confirm those arguments. If you confirm the condition without confirming the condition arguments, the arguments array will stay nil. While operands code generation is accounting for an empty arguments array with default values, it doesn't handle a nil array.
Rather than add a `or EMPTY` to every single `args` in the operands code generation (as is done in the editor, which is why the issue wasn't obvious to the user), I'm now setting the argsData to `EMPTY` instead of `nil` upon operand selection, and making sure on script generation that the arguments array isn't nil for good measure.
As a useless bonus, I fixed the boolean `hasPreview` returned on operand selection if preview is available. It's not actually used …
> Issue #153 : Make sure conditions arguments cannot be nil

- totalRP3_Extended/inventory/container.lua
- totalRP3_Extended/inventory/inventory.lua
Blizzard changed the OpenStackSplitFrame function to be called from the StackSplitFrame rather than standalone in 8.1, which broke the splitting function in Extended. First commit fixes this issue (#157).
While I was on the topic of splitting stacks, I went ahead and fixed issue #137 about splitting a stack by the maximum amount, which was leaving a "phantom" slot containing 0 occurences of the item. Splitting a stack by the maximum amount now leaves it untouched.
> Stack splitting bugfixes (#137/#157)

- totalRP3_Extended/inventory/inspection.lua
- totalRP3_Extended/inventory/inventory_drop.lua
- totalRP3_Extended/inventory/inventory_exchange.lua
- totalRP3_Extended/main.lua
- totalRP3_Extended/misc/sounds.lua
Some remaining calls to the old `TRP3_API.communication` API were either no longer working (my bad for not testing properly) or still using deprecated methods. This cleans everything to be in a correct state.
> Fix invalid or deprecated calls to Communications

- totalRP3_Extended/inventory/inspection.lua
- totalRP3_Extended/inventory/inventory_drop.lua
- totalRP3_Extended/inventory/inventory_exchange.lua
While testing the current 1.3.1 beta, I stumbled upon a few issues that needed fixing : 
- Deprecated Communications calls that weren't covered by the wrapper anymore (`getMessageIDAndIncrement` became `getNewMessageToken`, `addMessageIDHandler` became `registerMessageTokenProgressHandler`). The wrapper for `addMessageIDHandler` was actually wrong, so correcting those calls allowed to fix issues like the "Waiting for response" text at the bottom of the inspection window lingering.
- Deprecated calls to `TRP3_API.map.getCurrentCoordinates` (became `AddOn_TotalRP3.Map.getPlayerMapID` and `AddOn_TotalRP3.Map.getPlayerCoordinates`) which, while still valid in the current TRP3 release version, are obsolete with the dev branch cleaning. Better to fix those now while we're at it.
> Fixed Communications and Map deprecated calls
